// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('BucketList', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('BucketList', async function() {
    await driver.get("https://master.d1artn8nksk20o.amplifyapp.com/")
    await driver.setRect(1288, 1020)
    await driver.findElement(By.id("floating-button")).click()
    await driver.findElement(By.css("#mySidenav > a:nth-child(2)")).click()
    {
      const element = await driver.findElement(By.id("floating-button"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.id("floating-button")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("searchInput")).click()
    await driver.findElement(By.id("searchInput")).sendKeys("Canadian")
    await driver.findElement(By.id("EditEventButton")).click()
    await driver.findElement(By.id("searchInput")).click()
    await driver.findElement(By.id("EditEventButton")).click()
    await driver.findElement(By.id("searchInput")).click()
    await driver.findElement(By.id("searchInput")).sendKeys("Mexican")
    await driver.findElement(By.id("EditEventButton")).click()
    await driver.findElement(By.id("searchInput")).click()
    await driver.findElement(By.id("EditEventButton")).click()
  })
})
