// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Following', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Following', async function() {
    await driver.get("https://master.d1artn8nksk20o.amplifyapp.com/")
    await driver.setRect(1288, 1020)
    await driver.findElement(By.id("floating-button")).click()
    await driver.findElement(By.css("#mySidenav > a:nth-child(4)")).click()
    await driver.findElement(By.id("floating-button")).click()
    await driver.findElement(By.id("searchInput")).click()
    await driver.findElement(By.id("searchInput")).sendKeys("User One")
    await driver.findElement(By.id("EditEventButton")).click()
    await driver.findElement(By.id("searchInput")).click()
    await driver.findElement(By.id("searchInput")).click()
    await driver.findElement(By.id("EditEventButton")).click()
    await driver.findElement(By.id("searchInput")).click()
    await driver.findElement(By.id("searchInput")).sendKeys("User Two")
    await driver.findElement(By.id("EditEventButton")).click()
    await driver.findElement(By.id("searchInput")).click()
    await driver.findElement(By.id("EditEventButton")).click()
  })
})
